# ====================== GENERAL ======================
# Import additional configuration files

import = [
 "~/alacritty/themes/dracula/dracula.toml"
]

live_config_reload = true

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux a -t main || tmux new -s main"]

# ====================== ENV ======================
[env]

TERM = "alacritty"


# ====================== WINDOW ======================
[window]

dimensions = { columns = 135, lines = 50 } 

padding = { x = 1, y = 1 }

opacity = 0.95


# ====================== SCROLING ======================
[scrolling]


# ====================== FONT ======================
[font]

normal = {family = "Hack Nerd Font Mono", style = "Regular"}
bold = {family = "Hack Nerd Font Mono", style = "Bold"}
italic = {family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}

size = 12

offset = {x = 0, y = 1}


# ====================== COLORS ======================
[colors]


# ====================== BELL ======================
[bell]
command = { program = "osascript", args = ["-e", "beep"] }


# ====================== SELECTION ======================
[selection]


# ====================== CURSOR ======================
[cursor]


# ====================== TERMINAL ======================
[terminal]


# ====================== MOUSE ======================
[mouse]


# ====================== HINTS ======================
[hints]



[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
# binding = { key = "U", mods = "Control|Shift" }
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# ====================== KEYBOARD ======================
[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b\r" },
  { key = "N", mods = "Command", command = { program = "/Applications/Alacritty.app/Contents/MacOS/alacritty", args = ["msg", "create-window", "-e", "/bin/zsh", "-l", "-c", "$HOME/.config/tmux/scripts/alacritty_personal.sh"] } },
]


# ====================== DEBUG ======================
[debug]
